"use strict";
// <flexContainer> (ty=28) — CRUD, specialization validation, discovery.
//
// Each case carries the clause it is asserting. Two things about this resource type differ
// from every other one: (1) the envelope namespace prefix may not be m2m: (TS-0004:7.4.37.1),
// and (2) stateTag is incremented on custom attribute changes rather than on every UPDATE
// (TS-0001:9.6.35). Both are places where copying <container> gives the wrong behavior, so
// they are asserted explicitly.

const { test, before, after } = require("node:test");
const assert = require("node:assert/strict");
const { startServer } = require("./helpers/server");
const {
  create, retrieve, update, remove, discover,
  createRoot, uniqueRn, urils,
} = require("./helpers/onem2m");
const { startSink } = require("./helpers/noti-sink");

// registered under `specializations` in config/default.json
const CND = "http://developers.iotocean.org/schema/parkingBlock.xsd";
const KEY = "sc:parkingBlock";

let srv, root;

before(async () => {
  srv = await startServer();
  root = await createRoot(srv.baseUrl, "flx");
});

after(async () => {
  if (root) await root.remove();
  if (srv) await srv.stop();
});

function blockBody(rn, extra = {}) {
  return {
    [KEY]: {
      rn,
      cnd: CND,
      type: "ParkingBlock",
      name: rn,
      category: [],
      availableSpotNumber: 3,
      totalSpotNumber: 49,
      refParkingSpot: ["wdc_base/sync_parking/parkingLot_KETI/parkingSpot_001"],
      ...extra,
    },
  };
}

test("CREATE <flexContainer>: custom attributes round-trip unchanged", async () => {
  const rn = uniqueRn("blk");
  const res = await create(srv.baseUrl, root.sid, 28, blockBody(rn));

  assert.equal(res.rsc, "2001");
  const body = res.body[KEY];
  assert.ok(body, `envelope key should be ${KEY}: ${res.raw.slice(0, 200)}`);
  assert.equal(body.ty, 28);
  assert.equal(body.cnd, CND);
  assert.equal(body.availableSpotNumber, 3);
  assert.equal(body.totalSpotNumber, 49);
  assert.deepEqual(body.refParkingSpot, ["wdc_base/sync_parking/parkingLot_KETI/parkingSpot_001"]);
  assert.deepEqual(body.category, []);
  // TS-0004:7.4.37.1 table 7.4.37.1-2 — cs is NP, generated by the hosting CSE
  assert.equal(typeof body.cs, "number");
  assert.equal(body.st, 0);
});

test("RETRIEVE <flexContainer>: the envelope prefix is not rewritten to m2m:", async () => {
  // TS-0004:7.4.37.1 — "The XSD of <flexContainer> specializations may use a targetNamespace
  // other than the one identified by the m2m: prefix."
  const rn = uniqueRn("blk");
  await create(srv.baseUrl, root.sid, 28, blockBody(rn));

  const res = await retrieve(srv.baseUrl, `${root.sid}/${rn}`);
  assert.equal(res.rsc, "2000");
  assert.ok(res.body[KEY], `envelope key should be preserved: ${res.raw.slice(0, 200)}`);
  assert.equal(res.body["m2m:flx"], undefined);
  assert.equal(res.body[KEY].name, rn);
});

test("CREATE: missing cnd is rejected with 4000", async () => {
  // TS-0004:7.4.37.1 table 7.4.37.1-2 — containerDefinition is M on Create
  const rn = uniqueRn("blk");
  const body = blockBody(rn);
  delete body[KEY].cnd;

  const res = await create(srv.baseUrl, root.sid, 28, body);
  assert.equal(res.rsc, "4000");
});

test("CREATE: an unregistered cnd is rejected with 4125 SPECIALIZATION_SCHEMA_NOT_FOUND", async () => {
  // TS-0004:7.4.37.2.1 — "If the schema is not available then the Hosting CSE shall return ...
  // SPECIALIZATION_SCHEMA_NOT_FOUND". The RSC value is 4125 per TS-0004:6.6.3.5.
  const rn = uniqueRn("blk");
  const body = blockBody(rn);
  body[KEY].cnd = "http://example.org/schema/unknownThing.xsd";

  const res = await create(srv.baseUrl, root.sid, 28, body);
  assert.equal(res.rsc, "4125");
});

test("CREATE: an envelope key that disagrees with the specialization is rejected with 4000", async () => {
  const rn = uniqueRn("blk");
  const inner = blockBody(rn)[KEY];

  const res = await create(srv.baseUrl, root.sid, 28, { "m2m:parkingBlock": inner });
  assert.equal(res.rsc, "4000");
});

test("CREATE: a custom attribute the specialization does not declare is rejected with 4000", async () => {
  // TS-0004:7.4.37.2.1 — "If the received resource is not valid then ... BAD_REQUEST"
  const rn = uniqueRn("blk");
  const res = await create(srv.baseUrl, root.sid, 28, blockBody(rn, { bogusAttribute: 1 }));
  assert.equal(res.rsc, "4000");
});

test("CREATE: a declared custom attribute with the wrong type is rejected with 4000", async () => {
  const rn = uniqueRn("blk");
  const res = await create(srv.baseUrl, root.sid, 28, blockBody(rn, { availableSpotNumber: "three" }));
  assert.equal(res.rsc, "4000");
});

test("CREATE: a non-zero mni/mbs/mia is rejected with 5001 NOT_IMPLEMENTED", async () => {
  // TS-0004:7.4.37.2.1 step 3 — a non-zero mni/mbs/mia requires creating
  // <flexContainerInstance> children. That is out of scope here, so the attribute is rejected
  // rather than silently stored.
  const rn = uniqueRn("blk");
  const res = await create(srv.baseUrl, root.sid, 28, blockBody(rn, { mni: 10 }));
  assert.equal(res.rsc, "5001");

  const res2 = await create(srv.baseUrl, root.sid, 28, blockBody(uniqueRn("blk"), { mbs: 1024 }));
  assert.equal(res2.rsc, "5001");
});

test("CREATE: a disallowed parent resource type is rejected with 4108", async () => {
  // TS-0004:7.4.37.1 — parents are <CSEBase>, <AE>, <remoteCSE>, <container> (+ <flexContainer>)
  const cnt_rn = uniqueRn("c");
  await create(srv.baseUrl, root.sid, 3, { "m2m:cnt": { rn: cnt_rn } });
  const cin_rn = uniqueRn("i");
  const cin = await create(srv.baseUrl, `${root.sid}/${cnt_rn}`, 4, { "m2m:cin": { rn: cin_rn, con: "x" } });
  assert.equal(cin.rsc, "2001");

  const res = await create(srv.baseUrl, `${root.sid}/${cnt_rn}/${cin_rn}`, 28, blockBody(uniqueRn("blk")));
  assert.equal(res.rsc, "4108");
});

test("UPDATE: changing a custom attribute applies the value, increments st and recomputes cs", async () => {
  // TS-0001:9.6.35 — "This stateTag attribute value shall be incremented when a custom
  // attribute of the flexContainer is modified."
  // TS-0004:7.4.37.2.3 step 2b — contentSize is updated to the size of the custom attributes.
  const rn = uniqueRn("blk");
  const created = await create(srv.baseUrl, root.sid, 28, blockBody(rn));
  const st0 = created.body[KEY].st;
  const cs0 = created.body[KEY].cs;

  const res = await update(srv.baseUrl, `${root.sid}/${rn}`, {
    [KEY]: { availableSpotNumber: 7, refParkingSpot: ["a", "b", "c"] },
  });

  assert.equal(res.rsc, "2004");
  assert.equal(res.body[KEY].availableSpotNumber, 7);
  assert.deepEqual(res.body[KEY].refParkingSpot, ["a", "b", "c"]);
  assert.equal(res.body[KEY].st, st0 + 1);
  assert.notEqual(res.body[KEY].cs, cs0);
  // custom attributes absent from the request are preserved
  assert.equal(res.body[KEY].totalSpotNumber, 49);
});

test("UPDATE: changing only common attributes leaves st alone", async () => {
  // <container> increments st on every UPDATE (cse/resources/cnt.js), but a flexContainer's
  // stateTag only responds to custom attribute changes per TS-0001:9.6.35.
  const rn = uniqueRn("blk");
  const created = await create(srv.baseUrl, root.sid, 28, blockBody(rn));
  const st0 = created.body[KEY].st;

  const res = await update(srv.baseUrl, `${root.sid}/${rn}`, { [KEY]: { lbl: ["zone-a"] } });

  assert.equal(res.rsc, "2004");
  assert.deepEqual(res.body[KEY].lbl, ["zone-a"]);
  assert.equal(res.body[KEY].st, st0, "only a common attribute changed, so st must stay put");
});

test("UPDATE: cnd is write-once, so including it is rejected with 4000", async () => {
  // TS-0004:7.4.37.1 table 7.4.37.1-2 — containerDefinition is NP on Update
  const rn = uniqueRn("blk");
  await create(srv.baseUrl, root.sid, 28, blockBody(rn));

  const res = await update(srv.baseUrl, `${root.sid}/${rn}`, { [KEY]: { cnd: CND } });
  assert.equal(res.rsc, "4000");
});

test("UPDATE: sending null for a custom attribute removes it", async () => {
  const rn = uniqueRn("blk");
  await create(srv.baseUrl, root.sid, 28, blockBody(rn));

  const res = await update(srv.baseUrl, `${root.sid}/${rn}`, { [KEY]: { refParkingSpot: null } });
  assert.equal(res.rsc, "2004");
  assert.equal(res.body[KEY].refParkingSpot, undefined);
  assert.equal(res.body[KEY].totalSpotNumber, 49);
});

test("UPDATE: an undeclared custom attribute is rejected with 4000", async () => {
  const rn = uniqueRn("blk");
  await create(srv.baseUrl, root.sid, 28, blockBody(rn));

  const res = await update(srv.baseUrl, `${root.sid}/${rn}`, { [KEY]: { bogusAttribute: 1 } });
  assert.equal(res.rsc, "4000");
});

test("DELETE <flexContainer>", async () => {
  const rn = uniqueRn("blk");
  await create(srv.baseUrl, root.sid, 28, blockBody(rn));

  const res = await remove(srv.baseUrl, `${root.sid}/${rn}`);
  assert.equal(res.rsc, "2002");

  const after_del = await retrieve(srv.baseUrl, `${root.sid}/${rn}`);
  assert.equal(after_del.rsc, "4004");
});

test("<flexContainer> accepts <container>, <subscription> and <flexContainer> children", async () => {
  // TS-0001 table 9.6.35-1 / TS-0004 table 7.4.37.1-3
  const rn = uniqueRn("blk");
  await create(srv.baseUrl, root.sid, 28, blockBody(rn));
  const parent = `${root.sid}/${rn}`;

  const cnt = await create(srv.baseUrl, parent, 3, { "m2m:cnt": { rn: uniqueRn("c") } });
  assert.equal(cnt.rsc, "2001");

  const nested = await create(srv.baseUrl, parent, 28, blockBody(uniqueRn("blk")));
  assert.equal(nested.rsc, "2001", `nested <flexContainer> create failed: ${nested.raw.slice(0, 200)}`);
});

test("discovery: by ty=28 and by cnd", async () => {
  const rn = uniqueRn("blk");
  await create(srv.baseUrl, root.sid, 28, blockBody(rn));
  const sid = `${root.sid}/${rn}`;

  const by_ty = await discover(srv.baseUrl, root.sid, { ty: "28" });
  assert.equal(by_ty.rsc, "2000");
  assert.ok(urils(by_ty).includes(sid), `ty=28 discovery should contain ${sid}`);

  const by_cnd = await discover(srv.baseUrl, root.sid, { cnd: CND });
  assert.equal(by_cnd.rsc, "2000", `the cnd filter must not be rejected: ${by_cnd.raw.slice(0, 200)}`);
  assert.ok(urils(by_cnd).includes(sid), `cnd discovery should contain ${sid}`);

  // cnd is a column only <flexContainer> has. Mixed into the shared WHERE it would kill every
  // other type's query with "column cnd does not exist" (code map G-15/G-16) — only flx
  // resources may come back.
  const cnt_rn = uniqueRn("c");
  await create(srv.baseUrl, root.sid, 3, { "m2m:cnt": { rn: cnt_rn } });
  const filtered = await discover(srv.baseUrl, root.sid, { cnd: CND });
  assert.equal(filtered.rsc, "2000");
  assert.ok(!urils(filtered).includes(`${root.sid}/${cnt_rn}`), "a <container> must not match a cnd filter");

  // a different cnd must not match
  const other = await discover(srv.baseUrl, root.sid, { cnd: "http://example.org/nope.xsd" });
  assert.ok(!urils(other).includes(sid));
});

test("discovery: the cnd filter does not break discovery of other resource types", async () => {
  const cnt_rn = uniqueRn("c");
  await create(srv.baseUrl, root.sid, 3, { "m2m:cnt": { rn: cnt_rn } });

  const res = await discover(srv.baseUrl, root.sid, { ty: "3" });
  assert.equal(res.rsc, "2000");
  assert.ok(urils(res).includes(`${root.sid}/${cnt_rn}`));
});

test("notification: net=1 carries the sc: envelope through unchanged", async () => {
  const sink = await startSink();
  try {
    const rn = uniqueRn("blk");
    await create(srv.baseUrl, root.sid, 28, blockBody(rn));
    const parent = `${root.sid}/${rn}`;

    const sub = await create(srv.baseUrl, parent, 23, {
      "m2m:sub": { rn: uniqueRn("s"), nu: [sink.url], enc: { net: [1] } },
    });
    assert.equal(sub.rsc, "2001");

    await update(srv.baseUrl, parent, { [KEY]: { availableSpotNumber: 11 } });

    const noti = await sink.waitFor((i) => i.body && i.body["m2m:sgn"]);
    const rep = noti.body["m2m:sgn"].nev.rep;
    assert.ok(rep[KEY], `the notification rep envelope key should be ${KEY}: ${JSON.stringify(rep).slice(0, 200)}`);
    assert.equal(rep[KEY].availableSpotNumber, 11);
  } finally {
    await sink.stop();
  }
});
